4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np

Array = np.empty((2,2))
Array


array([[4.24608793e-315, 0.00000000e+000],
       [4.26410660e-315, 6.53396857e-310]])

2. Initialize an all one array with size 4X2.

In [ ]:
array = np.ones((4, 2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
Array = np.full((2,3),5)
Array

array([[5, 5, 5],
       [5, 5, 5]])

4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
A= np.array ([[1,2],[3,4]])
a=np.zeros_like(A)
a

array([[0, 0],
       [0, 0]])

5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
A = np.array([[4,5],[3,4]])
a = np.ones_like(A)
a


array([[1, 1],
       [1, 1]])

6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list=[1,2,3,4]
a=np.array(new_list)
a

array([1, 2, 3, 4])

Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
array = np.arange(10,50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
Array = np.arange(0,9)
Array = np.reshape(Array,(3,3))
Array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
Array = np.eye(3)
Array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
array = np.random.random(30)
mean = array.mean()
array, mean

(array([0.4698935 , 0.86486381, 0.32367708, 0.2586782 , 0.1973121 ,
        0.82081414, 0.99748646, 0.74357201, 0.22275558, 0.26713999,
        0.94692113, 0.7994774 , 0.21363408, 0.33502096, 0.90940456,
        0.10098089, 0.417897  , 0.72976082, 0.06734552, 0.31850616,
        0.19757109, 0.76281912, 0.49091863, 0.22200769, 0.79113363,
        0.31035668, 0.2991161 , 0.90924364, 0.97183006, 0.33055175]),
 np.float64(0.5096896592591291))

5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
Array = np.random.random((10,10))

print("Minimun Value:",Array.min())
print("Maximum Value:",Array.max())
Array

Minimun Value: 0.00235300906746827
Maximum Value: 0.9966748399104507


array([[0.35281028, 0.59889318, 0.30617089, 0.79890933, 0.55831306,
        0.12414783, 0.99667484, 0.04780336, 0.12860946, 0.30872698],
       [0.6438457 , 0.42214544, 0.48192387, 0.93881497, 0.86358034,
        0.48826669, 0.6171581 , 0.0759424 , 0.79538299, 0.25363473],
       [0.60727469, 0.40042408, 0.95462039, 0.82525119, 0.90485759,
        0.84622007, 0.07166728, 0.80824501, 0.95636198, 0.80769329],
       [0.87162253, 0.4082152 , 0.5501483 , 0.97573194, 0.19290246,
        0.14472152, 0.10520039, 0.32634636, 0.41412535, 0.43002722],
       [0.97823233, 0.22763269, 0.66305355, 0.27823472, 0.34922902,
        0.51848646, 0.96650691, 0.29455731, 0.46695475, 0.98694912],
       [0.3477506 , 0.4830874 , 0.8325458 , 0.88965844, 0.47976006,
        0.85968726, 0.28267054, 0.33720852, 0.87105713, 0.98986756],
       [0.41955906, 0.55644894, 0.40087597, 0.34334912, 0.56013352,
        0.48389927, 0.15428755, 0.22683972, 0.79079815, 0.00235301],
       [0.80543862, 0.15417697, 0.4312342

6. Create a zero array of size 10 and replace 5th element with 1.


In [ ]:
Array = np.zeros(10)
Array[4] = 1
Array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr = np.array([1,2,0,0,4,0])
reverse_arr = arr[::-1]
reverse_arr

array([0, 4, 0, 0, 2, 1])

8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
Rows, Cols=4,4
array = np.zeros((Rows,Cols), dtype=int)
array[0,:]=1
array[-1,:]=1
array[:,0]=1
array[:,-1]=1
array

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2,::2] = 1
checkerboard[::2,1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:

Array provided in the question.

In [ ]:
x = np.array(([1,2],[3,5]))
y = np.array(([5,6],[7,8]))
v = np.array(([9,10]))
w = np.array(([11,12]))

1. Add the two array.

In [ ]:
x_plus_y= x+y
v_plus_w= v+w

print("x + y :\n",x_plus_y)
print("v + w :\n",v_plus_w)

x + y :
 [[ 6  8]
 [10 13]]
v + w :
 [20 22]


2. Subtract the two array.

In [ ]:
x_sub_y = x-y
v_sub_w = v-w

print("x - y :\n",x_sub_y)
print("v - w :\n",v_sub_w)

x - y :
 [[-4 -4]
 [-4 -3]]
v - w :
 [-2 -2]


3. Multiply the array with any integers of your choice.

In [ ]:
x_multi_2 = x*2
v_multi_9 = v*9

print("x*2 :\n",x_multi_2)
print("v*9 :\n",v_multi_9)

x*2 :
 [[ 2  4]
 [ 6 10]]
v*9 :
 [81 90]


4. Find the square of each element of the array.

In [ ]:
x_squared = x**2
y_squared = y**2
v_squared = v**2
w_squared = w**2

print("x^2 :\n",x_squared)
print("y^2 :\n",y_squared)
print("v^2 :\n",v_squared)
print("w^2 :\n",w_squared)

x^2 :
 [[ 1  4]
 [ 9 25]]
y^2 :
 [[25 36]
 [49 64]]
v^2 :
 [ 81 100]
w^2 :
 [121 144]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
x_dot_v = np.dot(x,v)
x_dot_y = np.dot(x,y)
v_dot_w = np.dot(v,w)

print("x.v :\n",x_dot_v)
print("x.y :\n",x_dot_y)
print("v.w :\n",v_dot_w)

x.v :
 [29 77]
x.y :
 [[19 22]
 [50 58]]
v.w :
 219


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
concat_x_y_rows =np.concatenate((x,y),axis=0)
print("Concatination of x and y along rows:\n",concat_x_y_rows)

v_col=v.reshape(-1,1)
w_col=w.reshape(-1,1)
concat_v_w_cols = np.concatenate((v_col,w_col),axis=1)
print("Concatination of v and w along columns:\n",concat_v_w_cols)

Concatination of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatination of v and w along columns:
 [[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
try:
    concat_x_v=np.concatenate((x,v), axis=0)
except Exception as e:
    print("Error:\n", e)
    print("\nError explanation: Since x is 2x2 matrix while v is 1D matrix with size 2, the dimensions do not match. So, concatination is not possible")

Error:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Error explanation: Since x is 2x2 matrix while v is 1D matrix with size 2, the dimensions do not match. So, concatination is not possible


Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:





In [ ]:
A =np.array(([3,4],[7,8]))
B =np.array(([5,3],[2,1]))

1. Prove A.A^(−1) = I.

In [ ]:
A_inv = np.linalg.inv(A)
A1= np.dot(A,A_inv)
A1= np.round(A1,decimals=0)
print( A1,"\n A * A^(-1)=I proved")

[[1. 0.]
 [0. 1.]] 
 A * A^(-1)=I proved


2. Prove AB != BA.

In [ ]:
AB =np.dot(A,B)
BA =np.dot(B,A)
print("AB =\n",AB)
print("BA =\n",BA)
print("\n AB != BA proved")

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]

 AB != BA proved


3. Prove (AB)T = BTAT

In [ ]:
LHS= (AB).T
RHS = np.dot(B.T, A.T)
print("(AB)^T:\n", LHS)
print("B^T A^T:\n", RHS)
print("\n(AB)^T = B^T A^T proved")

(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]

(AB)^T = B^T A^T proved


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9


{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [ ]:
A = np.array([[2,-3,1],
               [1,-1,2],
               [3,1,-1]])

B = np.array([-1,-3,9])

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("(x, y, z) =", X)

(x, y, z) = [ 2.  1. -2.]


4.2 Experiment: How Fast is Numpy?

1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

In [ ]:
import time
n=1000000
L1 = list(range(n))
L2 = list(range(n))

start = time.time()
add = [L1[i] + L2[i] for i in range(n)]
end = time.time()

time_taken = end - start

print("Time taken by python :", time_taken ," seconds")

Time taken by python : 0.10262298583984375  seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
array1 = np.arange(n)
array2 = np.arange(n)

start = time.time()
add = array1 + array2
end = time.time()

time_taken = end - start

print("Time taken by numpy: ",time_taken," seconds")

Time taken by numpy:  0.0028314590454101562  seconds


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

In [ ]:
start = time.time()
multi = [L1[i] * L2[i] for i in range(n)]
end = time.time()

elapsed = end - start
print(f"Time taken by python: {end - start:.5f} seconds")

Time taken by python: 0.21166 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [62]:
start = time.time()
multi = array1 * array2
end = time.time()

print(f"Time taken by numpy: {end - start:.5f} seconds")

Time taken by numpy: 0.00504 seconds


3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

In [61]:
start = time.time()
dot = sum(L1[i] * L2[i] for i in range(n))
end = time.time()

print(f"Time taken by python: {end - start:.5f} seconds")

Time taken by python: 0.00029 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [60]:
start = time.time()
dot = np.dot(array1, array2)
end = time.time()

print(f"Time taken by numpy: {end - start:.5f} seconds")

Time taken by numpy: 0.00272 seconds


4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [59]:
n = 1000

matrix1= [list(range(n)) for _ in range(n)]
matrix2= [list(range(n)) for _ in range(n)]

start = time.time()
result_list = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(n))
                for j in range(n)]
               for i in range(n)]
end = time.time()

print(f"Time taken by python: {end - start:.5f} seconds")

Time taken by python: 190.88754 seconds


• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [63]:
matrix1 = np.arange(n*n).reshape(n, n)
matrix2= np.arange(n*n).reshape(n, n)

start = time.time()
result_np = np.dot(matrix1, matrix2)
end = time.time()

print(f"Time taken by numpy: {end - start:.5f} seconds")

Time taken by numpy: 4.44060 seconds
