# PART 1 — KNN CLASSIFICATION

In [84]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.datasets import load_iris

In [85]:
# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

In [86]:
# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [87]:
# Baseline KNN
knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [88]:
# Predictions
y_pred = knn.predict(X_test)

In [89]:
print("=== Baseline KNN ===")
print("Predictions for first 5 samples:", knn.predict(X_test[:5]))
print("Class probabilities for first 5 samples:", knn.predict_proba(X_test[:5]))
print("Test Accuracy:", accuracy_score(y_test, y_pred))

=== Baseline KNN ===
Predictions for first 5 samples: [1 0 2 1 1]
Class probabilities for first 5 samples: [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]
Test Accuracy: 1.0


In [90]:
# Hyperparameter Tuning — Best K
print("\n===Finding Best K for KNN===")


===Finding Best K for KNN===


In [91]:
# Try values of K from 1 to 30
param_grid_k = {
    "n_neighbors": list(range(1, 31))
}

In [92]:
# Define model
knn_simple = KNeighborsClassifier()

In [93]:
# 5-fold cross validation to find best K
knn_k_cv = GridSearchCV(
    estimator=knn_simple,
    param_grid=param_grid_k,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

In [94]:
knn_k_cv.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                                         23, 24, 25, 26, 27, 28, 29, 30]},
             scoring='accuracy')

In [95]:
# Show best K found
print("Best K value:", knn_k_cv.best_params_["n_neighbors"])
print("Best CV Accuracy:", knn_k_cv.best_score_)

Best K value: 3
Best CV Accuracy: 0.9583333333333334


In [96]:
# Use the best K model for predictions
best_knn = knn_k_cv.best_estimator_
best_knn_pred = best_knn.predict(X_test)

In [97]:
print("\n=== KNN with Best K ===")
print("Test Accuracy:", accuracy_score(y_test, best_knn_pred))
print("Classification Report:\n", classification_report(y_test, best_knn_pred))


=== KNN with Best K ===
Test Accuracy: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# PART 2 — LINEAR REGRESSION

In [98]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error

In [99]:
# Load student dataset
df = pd.read_csv('/content/drive/MyDrive/Concepts and Technologies of AI/student.csv')

In [100]:
# Feature and target
X = df.drop('Writing', axis=1)
y = df['Writing']

In [101]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [102]:
# Baseline Linear Regression
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression()

In [103]:
print("\n=== Baseline Linear Regression ===")
print("Coefficients:", lin_reg.coef_)
print("Intercept:", lin_reg.intercept_)


=== Baseline Linear Regression ===
Coefficients: [0.09212476 0.91363985]
Intercept: -1.538927419707349


In [104]:
# Predictions
y_train_pred = lin_reg.predict(X_train)
y_test_pred = lin_reg.predict(X_test)

In [105]:
# Evaluation
print("Train MSE:", mean_squared_error(y_train, y_train_pred))
print("Test MSE:", mean_squared_error(y_test, y_test_pred))

Train MSE: 20.42671379648373
Test MSE: 22.92523648341902


In [106]:
# Hyperparameter Tuning — Ridge & Lasso

# Range of α values
alpha_grid = {"alpha": np.logspace(-3, 0, 13)}  # 0.001 → 1.0

In [107]:
ridge = Ridge(random_state=42)
lasso = Lasso(random_state=42, max_iter=10000)

In [108]:
# Perform Grid Search CV for Ridge and Lasso
ridge_cv = GridSearchCV(ridge, alpha_grid, cv=5,
                        scoring="neg_mean_squared_error", n_jobs=-1)
lasso_cv = GridSearchCV(lasso, alpha_grid, cv=5,
                        scoring="neg_mean_squared_error", n_jobs=-1)

In [109]:
ridge_cv.fit(X_train, y_train)
lasso_cv.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=Lasso(max_iter=10000, random_state=42), n_jobs=-1,
             param_grid={'alpha': array([0.001     , 0.00177828, 0.00316228, 0.00562341, 0.01      ,
       0.01778279, 0.03162278, 0.05623413, 0.1       , 0.17782794,
       0.31622777, 0.56234133, 1.        ])},
             scoring='neg_mean_squared_error')

In [110]:
print("\n=== Hyperparameter Tuning (Ridge & Lasso) ===")
print("Best Ridge Alpha:", ridge_cv.best_params_["alpha"])
print("Best Ridge CV MSE:", -ridge_cv.best_score_)
print("Best Lasso Alpha:", lasso_cv.best_params_["alpha"])
print("Best Lasso CV MSE:", -lasso_cv.best_score_)


=== Hyperparameter Tuning (Ridge & Lasso) ===
Best Ridge Alpha: 1.0
Best Ridge CV MSE: 20.521736849527862
Best Lasso Alpha: 0.005623413251903491
Best Lasso CV MSE: 20.521654529872755


In [111]:
# Best models from GridSearchCV
best_ridge = ridge_cv.best_estimator_
best_lasso = lasso_cv.best_estimator_

In [112]:
# Predictions
ridge_train_pred = best_ridge.predict(X_train)
ridge_test_pred = best_ridge.predict(X_test)

In [113]:
lasso_train_pred = best_lasso.predict(X_train)
lasso_test_pred = best_lasso.predict(X_test)

In [114]:
print("\n=== Ridge Regression ===")
print("Coefficients:", best_ridge.coef_)
print("Train MSE:", mean_squared_error(y_train, ridge_train_pred))
print("Test MSE:", mean_squared_error(y_test, ridge_test_pred))


=== Ridge Regression ===
Coefficients: [0.09213514 0.91362602]
Train MSE: 20.426713811078994
Test MSE: 22.925202313725666


In [115]:
print("\n=== Lasso Regression ===")
print("Coefficients:", best_lasso.coef_)
print("Train MSE:", mean_squared_error(y_train, lasso_train_pred))
print("Test MSE:", mean_squared_error(y_test, lasso_test_pred))


=== Lasso Regression ===
Coefficients: [0.09220777 0.91354592]
Train MSE: 20.426714484075706
Test MSE: 22.924964900912222


 # PART 3 — LOGISTIC REGRESSION

In [116]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

In [117]:
# Load diabetes dataset
df = pd.read_csv('/content/drive/MyDrive/Concepts and Technologies of AI/diabetes.csv')

In [118]:
X = df.drop('Outcome', axis=1)
y = df['Outcome']

In [119]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [120]:
# ---------------- Baseline Logistic Regression ----------------
log_base = LogisticRegression(max_iter=1000)
log_base.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [121]:
y_pred = log_base.predict(X_test)

In [122]:
print("\n=== Baseline Logistic Regression ===")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))


=== Baseline Logistic Regression ===
Accuracy: 0.7467532467532467
Confusion Matrix:
 [[78 21]
 [18 37]]
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.79      0.80        99
           1       0.64      0.67      0.65        55

    accuracy                           0.75       154
   macro avg       0.73      0.73      0.73       154
weighted avg       0.75      0.75      0.75       154



In [123]:
# Hyperparameter Tuning
print("\nLogistic Regression Hyperparameter Tuning")

log_param_grid = {
    "C": np.logspace(-3, 3, 7),      # Strength of regularization
    "penalty": ["l1", "l2"],         # L1 (Lasso) or L2 (Ridge)
    "solver": ["liblinear"]          # Supports both penalties
}


Logistic Regression Hyperparameter Tuning


In [124]:
log_model = LogisticRegression(max_iter=1000)

In [125]:
log_cv = GridSearchCV(
    log_model,
    log_param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

In [126]:
log_cv.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(max_iter=1000), n_jobs=-1,
             param_grid={'C': array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03]),
                         'penalty': ['l1', 'l2'], 'solver': ['liblinear']},
             scoring='accuracy')

In [127]:
print("Best Parameters:", log_cv.best_params_)
print("Best CV Accuracy:", log_cv.best_score_)

Best Parameters: {'C': np.float64(1.0), 'penalty': 'l1', 'solver': 'liblinear'}
Best CV Accuracy: 0.7655204584832733


In [128]:
# Best tuned model
best_log = log_cv.best_estimator_
best_log_pred = best_log.predict(X_test)

In [129]:
print("\n=== Logistic Regression with Best Parameters ===")
print("Test Accuracy:", accuracy_score(y_test, best_log_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, best_log_pred))
print("Classification Report:\n", classification_report(y_test, best_log_pred))


=== Logistic Regression with Best Parameters ===
Test Accuracy: 0.7532467532467533
Confusion Matrix:
 [[80 19]
 [19 36]]
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.81      0.81        99
           1       0.65      0.65      0.65        55

    accuracy                           0.75       154
   macro avg       0.73      0.73      0.73       154
weighted avg       0.75      0.75      0.75       154

